import React from 'react';
import { Box, Heading, Text, VStack } from '@chakra-ui/react';

const TermsContent = () => {
  return (
    <VStack
      spacing={10}
      w="full"
      px="20px"
      py="60px"
      as="section"
      maxW="1000px"
      m="0 auto"
      alignItems="flex-start"
    >
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          ACCEPTANCE OF TERMS AND CONDITIONS
        </Heading>
        <Text>
          GSHV MEDIA LTD displays the content contained on this website
          (“Website” and or “Site“) and any and all information comprising the
          Website to you within the parameters of the terms and conditions of
          use of the GSHV MEDIA LTD website laid out herein (“Terms and
          Conditions“). By using, accessing, uploading or downloading any
          material or information to the Site, you will be deemed as being in
          acceptance of and agreed to the Terms and Conditions. If you do not
          wish to do so, please do not use, access, download and/or upload any
          information from the Site.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          CHANGES TO TERMS AND CONDITIONS
        </Heading>
        <Text>
          GSHV MEDIA LTD may at any time in its sole and total discretion modify
          these Terms and Conditions without notifying you. Your continued
          access and use of the Site will be subject to the Terms and Conditions
          valid at the time of said access. Accordingly, we advise you to review
          the Terms and Conditions periodically as your continued access or use
          of the Website shall be deemed as your acceptance of the amended Terms
          and Conditions.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          WEBSITE CONTENT
        </Heading>
        <Text>
          While all efforts are made to update the information and content
          displayed on this Site on a regular basis, GSHV MEDIA LTD shall not be
          bound in any manner by any information contained on the Website and
          shall be released from any and all liabilities to that effect. GSHV
          MEDIA LTD reserves the right to at any time adapt and or change any
          feature or aspect of the Site. No date, information or content
          contained on the Site (whether posted by GSHV MEDIA LTD; its direct/
          indirect subsidiaries or affiliated companies or a 3rd party) should
          be taken as advice. All content and material is offered only for
          informational purposes.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          THIRD PARTY WEBSITE LINKS
        </Heading>
        <Text>
          Direct and/or indirect links to affiliate and subsidiary companies of
          GSHV MEDIA LTD are provided on the Site for the user&apos;s
          convenience. GSHV MEDIA LTD however, retains no control over the
          information that is generated by, edited or removed from such sites
          and accepts no liability to this end. The use or reliance on the
          content linked to the Website does not imply advocacy by GSHV MEDIA
          LTD of such websites or the information and content therein. The
          reliance on and use of any such links is at the user&apos;s own risk
          and responsibility. No hypertext links are to be created from any site
          controlled by the user (whether directly or indirectly) to the Site
          without prior written permission of GSHV MEDIA LTD.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          INTELLECTUAL PROPERTY AND COPYRIGHTS
        </Heading>
        <Text mb={4}>
          All intellectual property rights and copyrights of all texts, logos,
          materials, content and data made available on the Site (collectively
          &quot;Materials&quot;) are owned by GSHV MEDIA LTD. GSHV MEDIA LTD is
          the lawful user thereof and GSHV MEDIA LTD&apos;s rights are protected
          by international and Cypriot intellectual property laws. As such, any
          unauthorized reproduction, copying, distribution, retransmission,
          sale, dissemination, publication, or other exploitation or circulation
          of the Materials will constitute an infringement of such intellectual
          property rights and copyright laws.
        </Text>
        <Text>
          The logos, names, trademarks and service marks (collectively
          &quot;Trademarks&quot;) displayed on the Website are the unregistered
          and registered Trademarks of GSHV MEDIA LTD. Nothing displayed on the
          Site should be interpreted as granting any license or rights to use
          any Trademark without prior written permission from GSHV MEDIA LTD.
          Without detracting from this, GSHV MEDIA LTD hereby authorizes the
          user to use and view the content and information displayed on this
          Site, provided that such content is used for informational purposes
          only.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          DISCLAIMER ON PUBLIC FORUMS & USER SUBMISSIONS
        </Heading>
        <Text mb={2}>
          GSHV MEDIA LTD accepts no responsibility for any Material submitted to
          the public areas by users of it&apos;s Site (including but not limited
          to chat rooms and or any other public area found on the Website). All
          Material (whether submitted by you or any other user) is not reviewed,
          approved or endorsed by GSHV MEDIA LTD. GSHV MEDIA LTD reserves the
          right to delete any and all Material submitted or posted by a user in
          the public arena, without notice, if it becomes aware that there is a
          possibility that you may:
        </Text>
        <Box as="ul" ml={8}>
          <li>
            <Text>
              Abuse, defame, harass, stalk, threaten or otherwise violate the
              rights of any other users and or any 3rd parties;
            </Text>
          </li>
          <li>
            <Text>
              Post, publish or disseminate any defamatory, indecent, obscene or
              unlawful information or content;
            </Text>
          </li>
          <li>
            <Text>
              Upload files containing viruses, corrupted files or any other
              similar software or programs that could damage the operation of
              GSHV MEDIA LTD&apos;s and/or a 3rd party&apos;s computer system or
              network;
            </Text>
          </li>
          <li>
            <Text>
              Violate any trademark, copyright or any other applicable laws or
              intellectual property rights of GSHV MEDIA LTD or any other 3rd
              party;
            </Text>
          </li>
          <li>
            <Text>
              Submit content containing promotional or marketing material with
              the intent to solicit business.
            </Text>
          </li>
        </Box>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          INFORMATION TRANSMISSION
        </Heading>
        <Text>
          The information transmitted via the internet to GSHV MEDIA LTD is
          susceptible to monitoring and interception. GSHV MEDIA LTD reserves
          the right to utilize independent verification in compliance with all
          applicable laws of any content or information transmitted and the
          user&apos;s consent to such verification should GSHV MEDIA LTD deem it
          necessary. The user further agrees not to use the Site to post or send
          any message, content or Material that is unlawful, defamatory,
          indecent, abusive, threatening, harmful, obscene, sexually orientated,
          racially offensive, or which violates any applicable laws. The user
          hereby indemnifies GSHV MEDIA LTD against any loss, liability, damage
          or expense of any nature which GSHV MEDIA LTD or any 3rd party may
          suffer as a result of, or attributable to, directly or indirectly,
          your use of the Website.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          WARRANTIES AND DISCLAIMERS
        </Heading>
        <Text>
          GSHV MEDIA LTD makes no warranties, representations, statements or
          guarantees (whether express, implied in law or residual) regarding the
          Website. To the extent permitted by applicable laws, GSHV MEDIA LTD
          can not be held responsible for any loss, liability, damage (whether
          consequential, direct or indirect ), expense or personal injury of any
          kind whatsoever which may or has been suffered by you or any 3rd
          party, as a result of, directly or indirectly, your access or use of
          the Site and any content contained on the Site. Furthermore, you waive
          any and all claims which you may hold against GSHV MEDIA LTD in this
          regard.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          GOVERNING LAW
        </Heading>
        <Text>
          Any claim relating to GSHV MEDIA LTD website shall be governed by the
          laws of Cyprus without regard to its conflict of law provisions.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          CONTACT
        </Heading>
        <Text mb={4}>
          GSHV MEDIA LTD is a digital marketing and tech services company based
          in Cyprus. The Company and the Company&apos;s website, it&apos;s brand
          and logo are owned and operated by GSHV MEDIA LTD. GSHV MEDIA LTD is
          registered in Cyprus, under company registration number HE426173 at
          the business address:
        </Text>
        <Text mb={4}>
          GSHV MEDIA LTD
          <br />
          Arch Makariou III,
          <br />
          256 Eftapaton Court,
          <br />
          3105, Limassol,
          <br />
          Cyprus
        </Text>
        <Text>
          Or email:
          <br />
          info@gshvmedia.com
        </Text>
      </Box>
    </VStack>
  );
};

export default TermsContent;
