import React from 'react';
import { Box, Heading, Text, VStack } from '@chakra-ui/react';

const PrivacyContent = () => {
  return (
    <VStack
      spacing={10}
      w="full"
      px="20px"
      py="60px"
      as="section"
      maxW="1000px"
      m="0 auto"
      alignItems="flex-start"
    >
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          WEBSITE PRIVACY POLICY COMPLIANT WITH GDPR (EU PRIVACY LAW)
        </Heading>
        <Text mb={4} fontWeight="bold">
          UPDATED ON OCTOBER 2nd, 2021.
        </Text>
        <Text mb={4}>
          GSHV MEDIA LTD (“we”, “us”, or “our”) operates the website
          www.gshvmedia.com (the “Website” or “Site”).
        </Text>
        <Text mb={4} fontWeight="bold">
          DEFINITIONS:
        </Text>
        <Text fontWeight="bold" fontStyle="italic">
          Website
        </Text>
        <Text mb={4}>
          https://www.gshvmedia.com This Website is operated by GSHV MEDIA LTD.
        </Text>
        <Text fontWeight="bold" fontStyle="italic">
          Personal Data
        </Text>
        <Text mb={4}>
          Data about an individual who may be identified from such data.
        </Text>
        <Text fontWeight="bold" fontStyle="italic">
          Usage Data
        </Text>
        <Text mb={4}>
          Data that is automatically collected and is either generated by the
          use of the Website or from the Website infrastructure itself.
        </Text>
        <Text fontWeight="bold" fontStyle="italic">
          Data Controller
        </Text>
        <Text mb={4}>
          Is the natural/legal person who determines the manner in which and the
          purposes for which collected personal information is to be processed.
          In this case, GSHV MEDIA LTD is the data Controller of your Personal
          Data.
        </Text>
        <Text fontWeight="bold" fontStyle="italic">
          Cookies
        </Text>
        <Text mb={4}>
          Small amounts of data stored on your browser in order to collect
          certain information.
        </Text>
        <Text fontWeight="bold" fontStyle="italic">
          Service Providers or Data Processors
        </Text>
        <Text mb={4}>
          Meaning any natural or legal person who processes data on behalf of
          the Data Controller. We may and can use the services of various
          Service Providers in order to process your data more efficiently.
        </Text>
        <Text fontWeight="bold" fontStyle="italic">
          Data Subject (or User)
        </Text>
        <Text mb={4}>
          Any living individual who is using our Site and is the subject of
          Personal Data.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          TYPES OF DATA COLLECTED
        </Heading>
        <Text fontWeight="bold" fontStyle="italic">
          Personal Data:
        </Text>
        <Text mb={4}>
          While using the Website, you may be asked to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (“Personal Data”). Personally identifiable information
          may include, but is not limited to:
        </Text>
        <Box as="ul" ml={8} mb={4}>
          <li>
            <Text>Full name</Text>
          </li>
          <li>
            <Text>Address, State, Province, ZIP/Postal code, City</Text>
          </li>
          <li>
            <Text>E-mail address</Text>
          </li>
          <li>
            <Text>Phone number</Text>
          </li>
          <li>
            <Text>Usage Data & Cookies Data</Text>
          </li>
        </Box>
        <Text fontWeight="bold" fontStyle="italic">
          Usage Data:
        </Text>
        <Text mb={4}>
          We may collect information about how our Website is accessed and used
          (“Usage Data”). This Usage Data may include information such as your
          computer’s IP address and browser type, as well as other unique device
          identifiers and other diagnostic data.
        </Text>
        <Text fontWeight="bold" fontStyle="italic">
          Tracking and Cookies Data:
        </Text>
        <Text>
          We use cookies as well as similar tracking technologies to track the
          activity on our Website, hold certain information and analyze and
          improve our Website.
          <br />
          Cookies are files with a small amount of data that may include a
          unique anonymous identifier. Cookies are sent to your browser from a
          website and stored on your device.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          USE OF DATA
        </Heading>
        <Text mb={2}>
          GSHV MEDIA LTD uses the previously mentioned collected data for
          various purposes:
        </Text>
        <Box as="ul" ml={8}>
          <li>
            <Text>
              To monitor the usage of and properly maintain our Website.
            </Text>
          </li>
          <li>
            <Text>To detect, prevent and address technical issues.</Text>
          </li>
          <li>
            <Text>
              To improve the functionality of interactive features of our
              Website when you choose to do so.
            </Text>
          </li>
        </Box>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          THE LEGAL GROUNDS FOR PROCESSING PERSONAL DATA UNDER THE GENERAL DATA
          PROTECTION REGULATION (GDPR)
        </Heading>
        <Text mb={4}>
          If you are from the European Economic Area (EEA), GSHV MEDIA LTD’s
          legal basis for collecting and using the personal information
          described in this Privacy Policy depends on the Personal Data we
          collect and the specific context in which we collect it.
        </Text>
        <Text mb={2}>
          GSHV MEDIA LTD can process your Personal Data for the purposes of:
        </Text>
        <Box as="ul" ml={8}>
          <li>
            <Text>
              To monitor the usage of and properly maintain our Website.
            </Text>
          </li>
          <li>
            <Text>To detect, prevent and address technical issues.</Text>
          </li>
          <li>
            <Text>
              To improve the functionality of interactive features of our
              Website when you choose to do so.
            </Text>
          </li>
        </Box>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          RETENTION OF DATA
        </Heading>
        <Text mb={4}>
          GSHV MEDIA LTD will retain your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
        </Text>
        <Text>
          GSHV MEDIA LTD will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of our Website.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          TRANSFER OF DATA
        </Heading>
        <Text mb={4}>
          Your information, including Personal Data, may be kept on or
          transferred to computers located outside of your state, country,
          province or other jurisdiction in which data protection laws may vary
          from those in your jurisdiction.
        </Text>
        <Text mb={4}>
          If you are located outside the EU and choose to provide information to
          us, please note that we transfer the data, including Personal Data to
          Cyprus and process it there.
        </Text>
        <Text mb={4}>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </Text>
        <Text mb={4}>
          GSHV MEDIA LTD will take all steps reasonably necessary to ensure that
          your data is treated securely and in accordance with this Privacy
          Policy, and no transfer of your Personal Data will take place to an
          organization or a country unless there are adequate controls in place,
          including the security of your data and other personal information.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          DISCLOSURE OF DATA BUSINESS TRANSACTION
        </Heading>
        <Text>
          If GSHV MEDIA LTD is involved in a merger, acquisition or asset sale,
          your Personal Data may be transferred. We will provide notice before
          your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          DISCLOSURE FOR LAW ENFORCEMENT
        </Heading>
        <Text>
          Under certain circumstances, GSHV MEDIA LTD may be required to
          disclose your Personal Data if required to do so by law or in response
          to valid requests by public authorities (e.g. a court or a government
          agency).
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          LEGAL REQUIREMENTS
        </Heading>
        <Text mb={2}>
          GSHV MEDIA LTD may disclose your Personal Data in the good faith
          belief that such action is necessary to:
        </Text>
        <Box as="ul" ml={8}>
          <li>
            <Text>To comply with a legal obligation.</Text>
          </li>
          <li>
            <Text>
              To protect and defend the rights or property of GSHV MEDIA LTD.
            </Text>
          </li>
          <li>
            <Text>
              To prevent or investigate possible wrongdoing in connection with
              the Website.
            </Text>
          </li>
          <li>
            <Text>
              To protect the safety of users of the Website or the public.
            </Text>
          </li>
          <li>
            <Text>To protect against legal liability.</Text>
          </li>
        </Box>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          SECURITY OF DATA
        </Heading>
        <Text>
          The security of your data is important to us, but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          “DO NOT TRACK” SIGNALS
        </Heading>
        <Text>
          We do not support Do Not Track (“DNT”). Do Not Track is a preference
          you can set in your web browser to inform websites that you do not
          want to be tracked. You can enable or disable Do Not Track by visiting
          the Preferences or Settings page of your web browser.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          YOUR DATA PROTECTION RIGHTS UNDER THE GENERAL DATA PROTECTION
          REGULATION (GDPR)
        </Heading>
        <Text mb={4}>
          If you are a resident of the European Economic Area (EEA), you have
          certain data protection rights. GSHV MEDIA LTD aims to take reasonable
          steps to allow you to correct, amend, delete, or limit the use of your
          Personal Data.
        </Text>
        <Text mb={4}>
          If you wish to be informed what Personal Data we hold about you, and
          if you want it to be removed from our systems, please contact us. In
          certain circumstances, you have the following data protection rights:
        </Text>
        <Text mb={4}>
          <strong>The right to access</strong>. update or delete the information
          we have on you. Whenever made possible, you can access, update or
          request deletion of your Personal Data directly within your account
          settings section. If you are unable to perform these actions yourself,
          please contact us to assist you.
        </Text>
        <Text mb={4}>
          <strong>The right of rectification</strong>. You have the right to
          have your information rectified if that information is inaccurate or
          incomplete.
        </Text>
        <Text mb={4}>
          <strong>‍The right to object</strong>. You have the right to object to
          our processing of your Personal Data.
        </Text>
        <Text mb={4}>
          <strong>The right of restriction</strong>. You have the right to
          request that we restrict the processing of your personal information.
        </Text>
        <Text mb={4}>
          <strong>The right to data portability</strong>. You have the right to
          be provided with a copy of the information we have on you in a
          structured, machine-readable and commonly used format.
        </Text>
        <Text mb={4}>
          <strong>The right to withdraw consent</strong>. You also have the
          right to withdraw your consent at any time where GSHV MEDIA LTD relied
          on your consent to process your personal information.
        </Text>
        <Text mb={4}>
          Please note that we may ask you to verify your identity before
          responding to such requests. You have the right to complain to a Data
          Protection Authority about our collection and use of your Personal
          Data. For more information, please contact your local data protection
          authority in the European Economic Area (EEA).
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          LINKS TO OTHER SITES
        </Heading>
        <Text>
          Our Website may contain links to other sites that are not operated by
          us. If you click on a 3rd party link, you will be directed to that 3rd
          party’s Site. We advise you to review the Privacy Policy of every site
          you visit. We have no control over and assume no responsibility for
          the content, privacy policies or practices of any third-party sites or
          services.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          CHILDREN’S PRIVACY
        </Heading>
        <Text mb={4}>
          Our Website does not address anyone under the age of 18 (“Children”).
          We do not knowingly collect personally identifiable information from
          anyone under the age of 18. If you are a parent or guardian and you
          are aware that your child has provided us with Personal Data, please
          contact us.
        </Text>
        <Text>
          If we become aware that we have collected Personal Data from children
          without verification of parental consent, we take steps to remove that
          information from our servers.
        </Text>
      </Box>
      <Box as="article">
        <Heading color="primary" mb={4} fontSize="30px">
          CHANGES TO THIS PRIVACY POLICY
        </Heading>
        <Text mb={4}>
          We may update our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page. We will
          let You know via e-mail and/or a prominent notice on our Website,
          prior to the change becoming effective and update the “Last Updated”
          date at the top of this Privacy Policy.
        </Text>
        <Text mb={4}>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page. If you have any questions about this Privacy
          Policy, please contact us:
        </Text>
        <Text mb={4}>
          GSHV MEDIA LTD
          <br />
          Arch Makariou III,
          <br />
          256 Eftapaton Court,
          <br />
          3105, Limassol,
          <br />
          Cyprus
        </Text>
        <Text>
          Or email:
          <br />
          info@gshvmedia.com
        </Text>
      </Box>
    </VStack>
  );
};

export default PrivacyContent;
